### ISSUE TITLE
Unable to play image on macOS 

### ISSUE THREAD

**Issue by stefanschramm** [stefanschramm/retroload#19]
macOS: 13.5.2 (22G91); speaker lib not installed; aplay and play not available

```
...% retroload rl.tap               
Format: KC .TAP-File, Target: kc
TypeError: Cannot read properties of null (reading 'toString')
    at AplayWrapper.<anonymous> (file:///Users/user0/retroload/retroload/dist/esm/player/AplayWrapper.js:20:44)
    at Generator.next (<anonymous>)
    at file:///Users/user0/retroload/retroload/dist/esm/player/AplayWrapper.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (file:///Users/user0/retroload/retroload/dist/esm/player/AplayWrapper.js:3:12)
    at AplayWrapper.create (file:///Users/user0/retroload/retroload/dist/esm/player/AplayWrapper.js:14:16)
    at file:///Users/user0/retroload/retroload/dist/esm/retroload.js:115:38
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/user0/retroload/retroload/dist/esm/retroload.js:5:58)
```

**Comment by stefanschramm** [comment]
[19-check-spawn.patch](https://github.com/stefanschramm/retroload/files/12612111/19-check-spawn.patch)
